site_name: 开发笔记
theme: readthedocs
pages:
    - 简介: 'index.md'
    - 链接: 'links/links.md'
    - 笔记:
        - 'Git': 'study/git.md'
        - 'JavaScript': 'study/javascript.md'
        - 'Mysql': 'study/mysql.md'
        - 'Vim': 'study/vim.md'
    - 知识:
        - '提问的智慧': 'study/ask-wisdom.md'
        - '快速学习Laravel': 'study/learn-laravel.md'
    - 软件:
        - 'Ubuntu-php-version': 'install/ubuntu.md'
        - 'ubuntu-mutiply-php-version': 'install/ubuntu-mutiply-php-version.md'
        - 'Ubuntu-lnmp': 'install/lnmp-shell.md'
        - 'Vim': 'install/vim.md'
        - 'Vsftpd': 'install/vsftpd.md'
        - 'Apache': 'install/httpd.md'
        - 'Mysql': 'install/mysql.md'
        - 'Php': 'install/php.md'
        - 'Git': 'install/git.md'
        - 'Redis': 'install/redis.md'
        - 'Memcached': 'install/memcached.md'
        - 'Mongodb': 'install/mongodb.md'
        - 'Composer': 'install/composer.md'
        - 'Mkdocs': 'install/mkdocs.md'
        - 'Gitbook': 'install/gitbook.md'
        - 'Node': 'install/node.md'
        - 'All': 'install/all.md'
    - 学习:
        - 'Laravel&ThinkPHP': 'study/laravel5-thinkphp5.md'
        - 'Laravel发送email': 'study/laravel-email.md'
        - 'ReadMe-Example': 'study/project-readme-example.md'
        - 'MarkDown': 'study/markdown.md'
