site_name: 开发笔记
theme: readthedocs
pages:
    - 简介: 'index.md'
    - 2018学习计划: 'learn-plan.md'
    - PHP笔记: 'php.md'
    - 官方文档: 'manual.md'
    - 链接: 'links.md'
    - Centos防火墙: 'firewalld.md'
    - PHP规范:
        - 'PSR-1 基础编码规范': 'psrs/psr-1-basic-coding.md'
        - 'PSR-2 编码风格规范': 'psrs/psr-2-coding-style.md'
        - 'PSR-3 日志接口规范': 'psrs/psr-3-log-interface.md'
        - 'PSR-4 自动加载规范': 'psrs/psr-4-autoload.md'
        - 'PSR-6 缓存接口规范': 'psrs/psr-6-cache-interface.md'
        - 'PSR-7 消息接口规范': 'psrs/psr-7-message-interface.md'
    - 学习:
        - 'Laravel技巧': 'laravel/laravel-skills.md'
        - 'Laravel&ThinkPHP': 'study/laravel5-thinkphp5.md'
        - 'Laravel发送email': 'study/laravel-email.md'
        - 'ReadMe-Example': 'study/project-readme-example.md'
        - 'MarkDown': 'study/markdown.md'
    - 笔记:
        - 'Vagrant': 'vagrant.md'
        - 'Lnmp': 'install/lnmp.md'
        - 'Git': 'study/git.md'
        - 'JavaScript': 'study/javascript.md'
        - 'Mysql': 'study/mysql.md'
        - 'Vim': 'study/vim.md'
        - 'Crontab': 'study/crontab.md'
    - 知识:
        - '如何学习PHP': 'study/learn-php.md'
        - '提问的智慧': 'study/ask-wisdom.md'
        - '快速学习Laravel': 'study/learn-laravel.md'
        - 'php面试题目': 'study/review.md'
    - 软件:
        - 'Ubuntu-php-version': 'install/ubuntu.md'
        - 'Ubuntu-mutiply-php-version': 'install/ubuntu-mutiply-php-version.md'
        - 'Ubuntu-lnmp': 'install/lnmp-shell.md'
        - 'Vim': 'install/vim.md'
        - 'Docker': 'install/docker.md'
        - 'Shadowsocks': 'install/shadowsocks.md'
        - 'Remote Link': 'install/remote.md'
        - 'Vsftpd': 'install/vsftpd.md'
        - 'Apache': 'install/httpd.md'
        - 'Mysql': 'install/mysql.md'
        - 'Php': 'install/php.md'
        - 'Git': 'install/git.md'
        - 'Redis': 'install/redis.md'
        - 'Memcached': 'install/memcached.md'
        - 'Mongodb': 'install/mongodb.md'
        - 'Composer': 'install/composer.md'
        - 'Mkdocs': 'install/mkdocs.md'
        - 'Gitbook': 'install/gitbook.md'
        - 'Node': 'install/node.md'
        - 'FileZilla': 'install/filezilla.md'
        - 'Xdebug': 'install/xdebug.md'
        - 'Wampserver-php': 'install/wampserver.md'
        - 'Sublime-text': 'install/sublimetext.md'
        - 'All': 'install/all.md'
