site_name: 开发笔记
theme: readthedocs
pages:
    - 简介: 'index.md'
    - phpstorm快捷键: 'study/phpstorm.md'
    - 2018学习计划: 'study/learn-plan.md'
    - 官方文档: 'study/manual.md'
    - 链接: 'study/links.md'
    - Centos防火墙: 'linux/firewalld.md'
    - Node-Sass: 'linux/node-sass.md'
    - PHP规范:
        - 'PSR-1 基础编码规范': 'books/psrs/psr-1-basic-coding.md'
        - 'PSR-2 编码风格规范': 'books/psrs/psr-2-coding-style.md'
        - 'PSR-3 日志接口规范': 'books/psrs/psr-3-log-interface.md'
        - 'PSR-4 自动加载规范': 'books/psrs/psr-4-autoload.md'
        - 'PSR-6 缓存接口规范': 'books/psrs/psr-6-cache-interface.md'
        - 'PSR-7 消息接口规范': 'books/psrs/psr-7-message-interface.md'
    - 学习:
        - 'Laravel技巧': 'laravel/laravel-skills.md'
        - 'Laravel&ThinkPHP': 'study/laravel5-thinkphp5.md'
        - 'Laravel发送email': 'laravel/laravel-email.md'
        - 'ReadMe-Example': 'laravel/project-readme-example.md'
        - 'MarkDown': 'study/markdown.md'
    - 笔记:
        - 'Vagrant': 'windows/vagrant.md'
        - 'Lnmp': 'linux/lnmp.md'
        - 'Git': 'study/git.md'
        - 'JavaScript': 'study/javascript.md'
        - 'Mysql': 'study/mysql.md'
        - 'MysqlPractice': 'study/mysql-practice-45.md'
        - 'Vim': 'study/vim.md'
        - 'Crontab': 'study/crontab.md'
    - 知识:
        - '如何学习PHP': 'study/learn-php.md'
        - '提问的智慧': 'study/ask-wisdom.md'
        - '快速学习Laravel': 'laravel/learn-laravel.md'
        - 'php面试题目': 'study/review.md'
    - 框架:
        - 'symfony': 'symfony/symfony.md'
    - 软件:
        - 'Ubuntu-php-version': 'linux/ubuntu.md'
        - 'Ubuntu-mutiply-php-version': 'linux/ubuntu-mutiply-php-version.md'
        - 'Ubuntu-lnmp': 'linux/lnmp-shell.md'
        - 'Vim': 'linux/vim.md'
        - 'Docker': 'linux/docker.md'
        - 'Shadowsocks': 'linux/shadowsocks.md'
        - 'Remote Link': 'linux/remote.md'
        - 'Vsftpd': 'linux/vsftpd.md'
        - 'Apache': 'linux/httpd.md'
        - 'Mysql': 'linux/mysql.md'
        - 'Php': 'linux/php.md'
        - 'Git': 'linux/git.md'
        - 'Redis': 'linux/redis.md'
        - 'Memcached': 'linux/memcached.md'
        - 'Mongodb': 'linux/mongodb.md'
        - 'Composer': 'linux/composer.md'
        - 'Mkdocs': 'linux/mkdocs.md'
        - 'Gitbook': 'linux/gitbook.md'
        - 'Node': 'linux/node.md'
        - 'FileZilla': 'linux/filezilla.md'
        - 'Xdebug': 'linux/xdebug.md'
        - 'Wampserver-php': 'windows/wampserver.md'
        - 'Sublime-text': 'linux/sublimetext.md'
        - 'All': 'linux/all.md'
